# values-local.yaml
# ArgoCD values para entorno local (kind)
# Sin HA, recursos mínimos, LoadBalancer para MetalLB

global:
  domain: argocd.local

configs:
  params:
    server.insecure: true  # Sin TLS para local

redis-ha:
  enabled: false

redis:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 1
  service:
    type: LoadBalancer

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

notifications:
  enabled: false

dex:
  enabled: false
