apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin
  namespace: apisix-apis
spec:
  loadbalancer:
    type: ewma
  timeout:
    connect: 5s
    read: 10s
    send: 10s
  retries: 3
  passHost: rewrite
  upstreamHost: httpbin-dev.local
  # aquí más adelante podemos añadir healthCheck, subsets, etc.
